name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            arch: x64
          - os: macos-14
            arch: arm64
          - os: windows-latest
            arch: x64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: pnpm run build:win

      - name: Build macOS
        if: startsWith(matrix.os, 'macos')
        run: pnpm run build && pnpm exec electron-builder --mac --${{ matrix.arch }}

      - name: List dist directory (Windows)
        if: matrix.os == 'windows-latest'
        run: Get-ChildItem -Force dist

      - name: List dist directory (macOS)
        if: startsWith(matrix.os, 'macos')
        run: ls -la dist

      - name: Release Windows asset
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/restful-api-test-*-setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release macOS assets
        if: startsWith(matrix.os, 'macos')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/restful-api-test-*-${{ matrix.arch }}.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
